version: '3.1'

services:
  discovery:
    container_name: consul
    image: consul:1.9
    ports:
      - "8500:8500"

  mysql-client:
    container_name: mysql-client
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_LOGIN: "root"
    ports:
      - "3306:3306"
    volumes:
      - ./bdd/client/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./bdd/client/table.sql:/docker-entrypoint-initdb.d/table.sql
      - ./data/mysql:/var/lib/mysql

  service-client:
    container_name: service-client
    image: service-client:latest
    restart: on-failure
    build:
      context: ./micro-client
      dockerfile: Dockerfile
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery
      - mysql-client
    ports:
      - "6868:8080"

  mongo-vente:
    container_name: mongo-vente
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: service_vente
    ports:
    - "27017:27017"
    volumes:
      - ./bdd/vente/setup.js:/docker-entrypoint-initdb.d/setup.js:ro
      - ./data/mongo/vente:/data/db

  service-vente:
    container_name: service-vente
    image: service-vente:latest
    restart: on-failure
    build:
      context: ./micro-vente
      dockerfile: Dockerfile
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery
      - mongo-vente
    ports:
      - "6871:8080"

volumes:
  data: