version: '3.1'

services:
  discovery:
    container_name: consul
    image: consul:1.9
    ports:
      - "8500:8500"

  mysql-client:
    container_name: mysql-client
    image: mysql:8.0
    restart: always

    command: --default-authentication-plugin=mysql_native_password
    
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_LOGIN: "root"

    ports:
      - "3306:3306"

    volumes:
      - ./bdd/client/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./bdd/client/table.sql:/docker-entrypoint-initdb.d/table.sql
      - ./data/mysql/client:/var/lib/mysql

  mongo-vente:
    container_name: mongo-vente
    image: mongo:latest
    restart: always

    environment:
      MONGO_INITDB_DATABASE: mongo_vente

    ports:
      - "27017:27017"
    volumes:
      - ./bdd/vente/setup-vente.js:/docker-entrypoint-initdb.d/setup-vente.js:ro
      - ./data/mongo/vente:/data/db

  mysql-catalogue:
    container_name: mysql-catalogue
    image: mysql:8.0
    restart: always

    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_LOGIN: "root"

    ports:
      - "3307:3306"

    volumes:
      - ./bdd/catalogue/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./bdd/catalogue/table.sql:/docker-entrypoint-initdb.d/table.sql
      - ./data/mysql/catalogue:/var/lib/

  mongo-social:
    container_name: mongo-social
    image: mongo:latest
    restart: always

    environment:
      MONGO_INITDB_DATABASE: service_social

    ports:
      - "27018:27017"

    volumes:
      - ./bdd/social/setup-social.js:/docker-entrypoint-initdb.d/setup-social.js:ro
      - ./bdd/social/insert-social.js:/docker-entrypoint-initdb.d/insert-social.js:ro
      - ./data/mongo/social:/data/db

volumes:
  data: