version: '3.1'

services:
  discovery:
    container_name: consul
    image: consul:1.9
    ports:
      - "8500:8500"

  mysql-client:
    container_name: mysql-client
    image: mysql:8.0
    restart: always

    command: --default-authentication-plugin=mysql_native_password
    
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_LOGIN: "root"

    ports:
      - "3306:3306"

    volumes:
      - ./bdd/client/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./bdd/client/table.sql:/docker-entrypoint-initdb.d/table.sql
      - ./data/mysql/client:/var/lib/mysql

  service-client:
    container_name: service-client
    image: service-client:latest
    restart: on-failure

    build:
      context: ./micro-client
      dockerfile: Dockerfile

    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery

    depends_on:
      - discovery
      - mysql-client

    ports:
      - "6868:8080"

  mysql-fournisseur:
    container_name: mysql-fournisseur
    image: mysql:8.0
    restart: always

    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_LOGIN: "root"

    ports:
      - "3309:3306"

    volumes:
      - ./bdd/fournisseur/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./bdd/fournisseur/table.sql:/docker-entrypoint-initdb.d/table.sql
      - ./data/mysql/fournisseur:/var/lib/mysql

  service-fournisseur:
    container_name: service-fournisseur
    image: service-fournisseur:latest
    restart: on-failure

    build:
      context: ./micro-fournisseur
      dockerfile: Dockerfile

    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery

    depends_on:
      - discovery
      - mysql-fournisseur

    ports:
      - "6869:8080"

volumes:
  data: